baseURL = "https://netadao.zone/"
languageCode = "en-us"
title = "Neta DAO"
theme = "hugograyscale"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    description = "The Community Accelerator - A DAO on Juno Network"

[Author]
    name = "Neta DAO"
    email = "netadao@protonmail.com"

[Social]
    twitter = "Neta_DAO"

[markup]
[markup.goldmark]
[markup.goldmark.rendered]
unsafe = true
