version: "2.0"

services:
  web:
    image: netadao/netadao-zone:v1
    expose:
      - port: 80
        as: 80
        accept:
          - netadao.zone
          - www.netadao.zone
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 256Mi
        storage:
          size: 256Mi
  placement:
    akash:
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        web: 
          denom: uakt
          amount: 500

deployment:
  web:
    akash:
      profile: web
      count: 1
